name: Build, Push Docker Image, and Restart ACI
on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest

    - name: Log out from Docker Hub
      run: docker logout

    - name: Log in to Azure
      if: success()
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Restart Azure Container Instance
      if: success()
      run: |
        az container restart --resource-group ${{ vars.RESOURCE_GROUP_NAME }} --name ${{ vars.CONTAINER_INSTANCE_NAME }}